{
 "title": "ABYSS Test - Internal Undersluice",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Undersluice - bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(undersluice_bytes_received{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "recvd"
    },
    {
     "expr": "increase(undersluice_bytes_sent{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Undersluice - sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "increase(undersluice_sessions_sent{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Undersluice - ntuples",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(undersluice_ntuples_received{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "recvd"
    },
    {
     "expr": "increase(undersluice_ntuples_active{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Deepcore Bytes - Input/Output",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(deepcore_input_bytes_total{instance=~\"deep-core-default-.+\",job=\"abyss\"}[30s])/2",
     "legendFormat": "input"
    },
    {
     "expr": "increase(deepcore_output_bytes_total{instance=~\"deep-core-default-.+\",job=\"abyss\"}[30s])/2",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Deepcore notifier bytes total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(deepcore_notifier_bytes_total{instance=~\"deep-core-default-.+\",job=\"abyss\"}[30s])/2",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Undersluice - packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(undersluice_packets_received{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "recvd"
    },
    {
     "expr": "increase(undersluice_packets_dropped{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "drop"
    }
   ]
  },
  {
   "title": "Haystack - Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(haystack_ingest_bytes{job=\"abyss\", instance=~\"haystack-.+\"}[30s])/2",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Haystack - Rows",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "increase(haystack_ingest_rows{job=\"abyss\", instance=~\"haystack-.+\"}[30s])/2",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Deepcore sessions - Input/Output",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(deepcore_input_sessions_total{instance=~\"deep-core-default-.+\",job=\"abyss\"}[30s])/2",
     "legendFormat": "input"
    },
    {
     "expr": "increase(deepcore_output_sessions_total{instance=~\"deep-core-default-.+\",job=\"abyss\"}[30s])/2",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Deepcore notifier sessions total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(deepcore_notifier_sessions_total{instance=~\"deep-core-default-.+\",job=\"abyss\"}[30s])/2",
     "legendFormat": "sess"
    }
   ]
  },
  {
   "title": "Undersluice - Totals (Range)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(undersluice_bytes_received{job=\"abyss\", instance=~\"undersluice-.+\"}[$__range]))",
     "legendFormat": "Bytes Received"
    },
    {
     "expr": "sum(increase(undersluice_bytes_sent{job=\"abyss\", instance=~\"undersluice-.+\"}[$__range]))",
     "legendFormat": "Bytes Sent"
    },
    {
     "expr": "sum(increase(undersluice_packets_received{job=\"abyss\", instance=~\"undersluice-.+\"}[$__range]))",
     "legendFormat": "Packets Received"
    },
    {
     "expr": "sum(increase(undersluice_packets_dropped{job=\"abyss\", instance=~\"undersluice-.+\"}[$__range]))",
     "legendFormat": "Packets Dropped"
    },
    {
     "expr": "sum(increase(undersluice_sessions_sent{job=\"abyss\", instance=~\"undersluice-.+\"}[$__range]))",
     "legendFormat": "Sessions Sent"
    },
    {
     "expr": "sum(increase(undersluice_ntuples_received{job=\"abyss\", instance=~\"undersluice-.+\"}[$__range]))",
     "legendFormat": "Ntuples Received"
    }
   ]
  },
  {
   "title": "Undersluice- Avg Rates (Range)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(undersluice_packets_received{job=\"abyss\",instance=~\"undersluice-.+\"}[$__range])) / $__range_s",
     "legendFormat": "Packets Recvd per second"
    },
    {
     "expr": "avg(increase(undersluice_bytes_received{job=\"abyss\",instance=~\"undersluice-.+\"}[$__range])) / $__range_s",
     "legendFormat": "Bytes Recvd per second"
    },
    {
     "expr": "avg(increase(undersluice_bytes_sent{job=\"abyss\", instance=~\"undersluice-.+\"}[$__range])) / $__range_s",
     "legendFormat": "Bytes Sent per second"
    },
    {
     "expr": "avg(increase(undersluice_sessions_sent{job=\"abyss\",instance=~\"undersluice-.+\"}[$__range])) / $__range_s",
     "legendFormat": "Sessions Out per second"
    }
   ]
  },
  {
   "title": "Deepcore - Totals (Range)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(deepcore_input_bytes_total{instance=~\"deep-core-default-.+\",job=\"abyss\"}[$__range]))",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "sum(increase(deepcore_output_bytes_total{instance=~\"deep-core-default-.+\",job=\"abyss\"}[$__range]))",
     "legendFormat": "Bytes Out"
    },
    {
     "expr": "sum(increase(deepcore_input_sessions_total{instance=~\"deep-core-default-.+\",job=\"abyss\"}[$__range]))",
     "legendFormat": "Sessions In"
    },
    {
     "expr": "sum(increase(deepcore_output_sessions_total{instance=~\"deep-core-default-.+\",job=\"abyss\"}[$__range]))",
     "legendFormat": "Sessions Out"
    },
    {
     "expr": "avg(increase(deepcore_processing_time{instance=~\"deep-core-default-.+\", job=\"abyss\"}[$__range]))",
     "legendFormat": "Avg Processing Time"
    },
    {
     "expr": "sum(increase(deepcore_signature_hits_total{instance=~\"deep-core-default-.+\", job=\"abyss\"}[$__range]))",
     "legendFormat": "Signature Hits"
    }
   ]
  },
  {
   "title": "Deepcore Signature Hits Total (Range)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(signature) (increase(deepcore_signature_hits_total{instance=~\"deep-core-default-.+\", job=\"abyss\"}[$__range]))",
     "legendFormat": "{{signature}}"
    }
   ]
  },
  {
   "title": "Undersluice - current output queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(undersluice_current_output_queue{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "queue"
    }
   ]
  },
  {
   "title": "Undersluice - current step",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "increase(undersluice_current_step{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "step"
    }
   ]
  },
  {
   "title": "Undersluice - current priority",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "increase(undersluice_current_priority{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "priority"
    }
   ]
  },
  {
   "title": "Deepcore Signature Hits Per Pod (Range)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(deepcore_signature_hits_total{instance=~\"deep-core-default-.+\", job=\"abyss\"}[$__range]))",
     "legendFormat": "{{signature}}"
    }
   ]
  },
  {
   "title": "Undersluice - defrag datastore bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(undersluice_defrag_datastore_bytes{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Undersluice - input buffer current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "increase(undersluice_input_buffer_current{job=\"abyss\", instance=~\"undersluice-.+\"}[30s])/2",
     "legendFormat": "buffer"
    }
   ]
  },
  {
   "title": "Deepcore Signature Hits Total Since Pod Started",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deepcore_signature_hits_total{instance=~\"deep-core-default-.+\", job=\"abyss\"}",
     "legendFormat": "{{instance}} - {{signature}}"
    }
   ]
  },
  {
   "title": "Pod/Container Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "up{instance=~\"undersluice-.+\", job=\"abyss\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{instance=~\"deep-core-default-.+\", job=\"abyss\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}